[package]
edition = "2021"
name = "aoc2022"
version = "0.1.0"

description = "Advent of Code 2022"
authors = ["Gabriel Fontes <hi@m7.rs>"]
license = "Unlicense"

[dependencies]
anyhow = "1.0"

[[bin]]
name = "day5"
path = "src/day5/main.rs"

[[bin]]
name = "day6"
path = "src/day6/main.rs"
